### ISSUE TITLE
[Front] Footer

### ISSUE THREAD

**Issue by Abibibi** [Instant-Visio/InstantVisio-WebApp#17]
With following links:

- Legal Mentions
- Personal Data
- FAQ
- Credits / team / backers (daily.co, ovh, twilio)
- Blog (promis un post aux founders de daily)
- Contact

**Comment by Abibibi** [comment]
Footer created & Legal Mentions, Personal Data, Credits, Blog and Contact links done. FAQ still missing

**Comment by HugoGresse** [comment]
it's done no?

**Comment by Abibibi** [comment]
FAQ is still missing but we can open an issue specifically for this
