### ISSUE TITLE
Firebase functions version

### ISSUE THREAD

**Issue by MattiaPrimavera** [Instant-Visio/InstantVisio-WebApp#175]
Which versions of `firebase-functions` npm package is currently in use ? Shouldn't that be added within `devDependencies` ?

**Comment by HugoGresse** [comment]
Firebase functions is present in package.json here https://github.com/Instant-Visio/InstantVisio-WebApp/blob/master/functions/package.json#L20

**Comment by MattiaPrimavera** [comment]
It seems it has been removed from current [package.json file](https://github.com/Instant-Visio/InstantVisio-WebApp/blob/master/package.json) on `master` branch, creating a little issue for that ;)

**Comment by HugoGresse** [comment]
the link is correct and it is on master

no need for a new issue

**Comment by MattiaPrimavera** [comment]
Am I looking in the wrong spot ? I don't see that within the file I linked although ^^'

**Comment by HugoGresse** [comment]
https://github.com/Instant-Visio/InstantVisio-WebApp/blob/master/functions/package.json#L20

vs 
https://github.com/Instant-Visio/InstantVisio-WebApp/blob/master/package.json

**Comment by MattiaPrimavera** [comment]
Ok closed the new issue, my bad :)
