### ISSUE TITLE
Video call page not found

### ISSUE THREAD

**Issue by MattiaPrimavera** [Instant-Visio/InstantVisio-WebApp#218]
Video call page is not accessible before a call was started

**Comment by HugoGresse** [comment]
What's the issue there? We cannot join a call where there is no call no?

**Comment by MattiaPrimavera** [comment]
Premise: all issues with `mobile` label concern `ionic-react` (also linked to the milestone).

The video page can be accessed from the left menu on mobile portrait view, but it currently leads to *page not found* message for the moment.

A better message to the user would be a page with something like

> no video call has started yet

for instance

**Comment by HugoGresse** [comment]
no we need to have the "Video" call button on the menu at all? What's the point of having a button that redirec tto nowhere? Maybe we could block the user on the call (no back button for ex) until he manually press "Leave call" no?

**Comment by MattiaPrimavera** [comment]
Same as for `RN`: the user may quit the application or a started video call through the back button: in this case, he may wanna join the call again, and a way to navigate to that page without having to click again on an invite link may come useful (above all if the user is the one who started the call => he would have no invite link to click on)
