### ISSUE TITLE
Status bar overlaying the app bar

### ISSUE THREAD

**Issue by MattiaPrimavera** [Instant-Visio/InstantVisio-WebApp#272]
tested on iPhone 8 simulator:

<img width="442" alt="Screenshot 2020-07-15 at 00 41 20" src="https://user-images.githubusercontent.com/11927970/87483451-099b6780-c634-11ea-9ce1-3db09bac00cd.png">

The issue is even more visible in phones containing the camera at the top of the screen (like iPhone 11)

**Comment by kangadominique123** [comment]
it s okay now for ios.
<img width="559" alt="Capture d’écran 2020-11-15 à 23 46 59" src="https://user-images.githubusercontent.com/27282579/99199151-6acb7700-279d-11eb-9464-48e0186662cd.png">
