### ISSUE TITLE
Restructure routing

### ISSUE THREAD

**Issue by MattiaPrimavera** [Instant-Visio/InstantVisio-WebApp#399]
- check if to update `react-router`
- nest routes with a main router and Switches: the switch routes should render when the user navigates through the app, the top bar should not be rendered again
- AppBar should access `history` object, in order to control navigation

**Comment by HugoGresse** [comment]
CF using a top router and many switch : https://reactrouter.com/web/example/nesting

**Comment by MattiaPrimavera** [comment]
I moved the `AppBar` inside the router, so that it can access the `history`, whereas it is re-rendered on page change. I don't see the difference for the moment although, in terms of user experience
