### ISSUE TITLE
Page pricing

### ISSUE THREAD

**Issue by MattiaPrimavera** [Instant-Visio/InstantVisio-WebApp#402]
pricing data : 
200€ / ans : https://www.helloasso.com/associations/instant-visio/paiements/souscription-au-service-premium
1000 € / ans https://www.helloasso.com/associations/instant-visio/paiements/compte-premium-br-i-10-000-credits-visio-br-500-credits-invitations-sms-i

Pore info : https://www.notion.so/8e9e570c80874358907caf8e37ec9fa5?v=eac5bdffdfef446aaa10a6f92c9f7c48&p=fc6c8ffe0dba4886b4a3a9d27c68d63c

**Comment by MattiaPrimavera** [comment]
Further instructions on slack

**Comment by NicolasHov** [comment]
see there -> https://github.com/Instant-Visio/InstantVisio-WebApp/pull/539

**Comment by MattiaPrimavera** [comment]
You can link the PR with this issue either
- on the right of this page
- or inside the PR page
