### ISSUE TITLE
DateTimePicker component freezing UI on chrome

### ISSUE THREAD

**Issue by MattiaPrimavera** [Instant-Visio/InstantVisio-WebApp#452]

**Comment by ntchou** [comment]
tested with chrome `86` and chrome `87`. It's work

**Comment by MattiaPrimavera** [comment]
It seems it doesn't on `chrome` for macOS `87`

**Comment by MattiaPrimavera** [comment]
it seems to come from a Chrome plugin of mine, since it works in anonymous navigation
