### ISSUE TITLE
Send timezone when creating a room

### ISSUE THREAD

**Issue by MattiaPrimavera** [Instant-Visio/InstantVisio-WebApp#493]
use `Europe/Paris` by default (check the format)

**Comment by HugoGresse** [comment]
use Intl API: Intl.DateTimeFormat().resolvedOptions().timeZone to retrieve it.
Send it to createRoom.

**Comment by ntchou** [comment]
fixed in this pr 
https://github.com/Instant-Visio/InstantVisio-WebApp/pull/602
