### ISSUE TITLE
Create a group

### ISSUE THREAD

**Issue by MattiaPrimavera** [Instant-Visio/InstantVisio-WebApp#548]
A premium user should be able to create a group. A group allows to send invites by push notifications.

We don't have wireframes yet. Add:
- basic form component to add a group (the group name is the only input)
- network layer (*api.ts*)
- async action
- refresh groups after creation

**Comment by HugoIneat** [comment]
@MattiaPrimavera

You say that the group name is the only input but if I look at the swagger, it seems that a password is needed.

https://instantvisio-dev.web.app/api/v1-docs/#/groups/post_v1_groups_

**Comment by HugoGresse** [comment]
it is, the password is user choosen, maybe set a min of 4 char as a password.
