### ISSUE TITLE
Support more "sms" country 

### ISSUE THREAD

**Issue by stephanelucon** [Instant-Visio/InstantVisio-WebApp#66]
![Screenshot 2020-03-29 at 20 38 28](https://user-images.githubusercontent.com/47471662/77857638-00aa9580-71ff-11ea-98de-e4cf48724aec.png)

**Comment by Abibibi** [comment]
additional screenshot
![screenshot_2020-03-29_at_21 00 35](https://user-images.githubusercontent.com/50984435/77874330-e8616780-724c-11ea-9aca-07490f175acd.png)

**Comment by HugoGresse** [comment]
I've tested it without having any issue. So the sms with the indicatif (+40 here) is always sent
